<?php include 'header.php';?>
 <div class="container mt-8">
    <h1 class="mb-8 text-center" >Kebijakan Privasi - PT Pusat Gadai Indonesia</h1>
    <h2>Halo Sobat Gaol!</h2>
    <p>Kebijakan Privasi ini berlaku untuk layanan-layanan yang disediakan oleh PT Pusat Gadai Indonesia dan menjelaskan terkait pengumpulan, penggunaan, penyimpanan, perbaikan, pembaharuan, penampilan, pengumuman, transfer, penyebarluasan, pengungkapan, penghapusan, dan pemusnahan Data Pribadi milik Anda yang Kami peroleh dari penggunaan Gadai Online oleh Anda, dan situs yang dimiliki oleh Kami termasuk yang memiliki alamat situs di.... (masing-masing disebut “Aplikasi Gadai Online” dan “Situs”, dan secara bersama-sama disebut “Aplikasi/Situs Gadai Online”)
    Setiap Data Pribadi yang telah dituangkan di Aplikasi/Situs Gadai Online diperuntukkan khusus untuk PT Pusat Gadai Indonesia. Kami menggunakan Data Pribadi Anda hanya untuk kebutuhan pengembangan dan peningkatan kualitas layanan Gadai Online atau kebutuhan lainnya yang wajar dan tidak bertentangan dengan peraturan perundang-undangan yang berlaku di Indonesia serta apa yang disebutkan dalam Kebijakan Privasi ini.
    Dengan mengeklik “Masuk” atau pernyataan serupa yang tersedia di laman pendaftaran Aplikasi Gadai Online atau pada saat Anda memberikan persetujuan Anda atas setiap perubahan dari Kebijakan Privasi Kami, Pengguna menyatakan bahwa setiap Data Pribadi Pengguna merupakan data yang benar sah, Pengguna mengakui bahwa telah diberitahukan dan memahami ketentuan Kebijakan Privasi ini serta Pengguna memberikan persetujuan kepada PT Pusat Gadai Indonesia untuk memperoleh, mengumpulkan, mengolah, menganalisis, menampilkan, mengirimkan, membuka, menyimpan, mengubah, menghapus, mengelola dan/atau mempergunakan data tersebut untuk tujuan sebagaimana tercantum dalam Kebijakan Privasi ini.</p>
     <h2 style="font-size: 18px;">1. Pengumpulan dan Penggunaan Data Pribadi</h2>
    <p>Anda dengan ini memberikan persetujuan bahwa pada saat Anda pertama kali menggunakan Gadai Online dan di waktu kapanpun saat Anda menggunakan Gadai Online, PT Pusat Gadai Indonesia dapat meminta Anda atau meminta pihak ketiga yang menyimpan Data Pribadi milik Anda yang sebelumnya pihak ketiga tersebut telah mendapatkan persetujuan dari Anda untuk memberikan beberapa informasi Data Pribadi yang akan Kami gunakan untuk hal-hal yang disebutkan dalam Kebijakan Privasi ini, keperluan pengadaan layanan Gadai Online, untuk keperluan penegakan hukum dan kepatuhan atas peraturan perundang-undangan yang berlaku, serta mengidentifikasi dan menghubungi Anda. Informasi data pribadi termasuk namun tidak terbatas pada:</p>
    <ul>
      <li>Nama</li>
      <li>Nomor Ponsel</li>
      <li>Alamat lengkap</li>
      <li>Data KTP</li>
    </ul>
    <p>Data Pribadi milik Anda akan digunakan oleh PT Pusat Gadai Indonesia untuk keperluan penyediaan layanan Aplikasi Gadai Online, tapi tidak terbatas dalam melakukan verifikasi atas Data Pribadi milik Anda, memproses Pendaftaran Anda sebagai pengguna dalam Aplikasi Gadai Online, mengolah transaksi yang Anda lakukan di Aplikasi Gadai Online, pencegahan dan penanganan tindakan fraud/pencucian uang/pendanaan terorisme, keperluan administratif internal seperti audit, keperluan promosi dan pemasaran, serta pengembangan dan pemeliharaan layanan Aplikasi Gadai Online, serta untuk keperluan penegakan hukum dan kepatuhan atas peraturan perundang-undangan yang berlaku.</p>
    
    <h2 style="font-size: 18px;">2. Penggunaan, Penyimpanan, Pemanfaatan, dan Pengolahan Data Pribadi</h2>
    <p>PT Pusat Gadai Indonesia berkomitmen untuk menjaga kerahasiaan Data Pribadi Anda yang berada di bawah kendali PT Pusat Gadai Indonesia dan menjamin tidak ada pengungkapan, penjualan, pengalihan, distribusi, dan/atau peminjaman Data Pribadi Anda kepada pihak ketiga lain termasuk kepada afiliasi Kami, tanpa persetujuan dari Anda, kecuali dalam hal-hal sebagai berikut:</p>
    <ul>
      <li>Melakukan identifikasi, mengadministrasikan, memverifikasikan, menonaktifkan, atau mengelola akun pada Aplikasi Gadai Online Anda;</li>
      <li>Menyediakan layanan yang Anda butuhkan, termasuk layanan-layanan yang tersedia pada Aplikasi Gadai Online;</li>
      <li>Memberikan fasilitas pengajuan gadai dan transaksi pembayaran yang Anda lakukan melalui Aplikasi Gadai Online;</li>
      <li>Memantau dan atau menganalisis penggunaan atau pengelolaan Aplikasi demi mendukung efisiensi dan efektivitas Aplikasi dan fungsi-fungsi lain di dalamnya, termasuk pola penggunaan Aplikasi serta berbagai layanan yang tersedia di dalamnya;</li>
      <li>Mencegah, mendeteksi, dan/atau menyelidiki segala kegiatan yang dilarang, tidak sah, tidak sesuai hukum, atau merupakan sesuatu bentuk kecurangan apapun, termasuk transaksi yang mencurigakan, penipuan, pencucian uang, dan/atau pendanaan terorisme;</li>
      <li>Mengembangkan bisnis, produk, mutu, dan pelayanan, termasuk kegiatan promosi, studi, riset, lainnya untuk pengembangan tersebut;</li>
      <li>Melakukan pemrosesan pada data teknis Anda seperti, internet protocol address, identitas (ID) perangkat internet atau alamat kontrol akses media (media access control address), informasi mengenai pabrikan, model, dan sistem operasi dari perangkat yang Anda gunakan untuk mengakses Aplikasi , akses ke kontak yang digunakan untuk mempermudah transaksi Gadai Online dengan sesama pengguna dan akses ke Global Positioning System (GPS) untuk dapat memberikan info posisi cabang Pusat Gadai Indonesia yang terdekat dengan lokasi Anda. Kami menggunakan data ini untuk memungkinkan Kami mengirimkan fungsi-fungsi dari Aplikasi, menyelesaikan kesulitan-kesulitan teknis, menyediakan bagi Anda versi Aplikasi/Situs yang benar dan terkini serta untuk meningkatkan fungsi Aplikasi/Situs;</li>
      <li>Kegiatan promosi dan periklanan yang meliputi namun tidak terbatas pada pengidentifikasi iklan, untuk memfasilitasi Kami dalam melakukan analitik atau penyediaan konten promosi atau informasi lain yang mungkin relevan bagi Anda;</li>
      <li>Mengembangkan Layanan baru dan meningkatkan Layanan yang ada dan memberikan Anda informasi tentang konten produk terkait, layanan dan perangkat lunak termasuk untuk berkomunikasi dengan Pengguna tentang berbagai cara yang mereka gunakan, misalnya untuk menyediakan atau mengirim kepada Anda;</li>
      <li>Mengelola dan mengembangkan bisnis dan operasional PT Pusat Gadai Indonesia atau Anda;</li>
      <li>Hal-hal yang diwajibkan dan/atau diminta oleh institusi, regulator dan/atau aparat penegak hukum yang berwenang berdasarkan ketentuan hukum yang berlaku, somasi, perintah resmi dari Pengadilan, dan/atau perintah resmi dari instansi atau aparat yang bersangkutan, termasuk namun tidak terbatas pada perselisihan, penyelidikan, penyidikan, proses hukum dan proses penyelesaian sengketa antara Kami dengan Anda selaku Pengguna, antar-Pengguna, dan Pengguna dengan pihak lainnya serta kegiatan ilegal lainnya; dan/atau</li>
      <li>Mengungkapkan dan/atau memberikan Data Pribadi Anda kepada pihak-pihak yang berkepentingan dalam rangka pelaksanaan analisis kelayakan kredit Anda</li>
      <li>Tujuan lain yang disampaikan dari waktu ke waktu, serta diizinkan atau diwajibkan oleh hukum dan peraturan yang berlaku.</li>
    </ul>
    <p>Sehubungan dengan pengungkapan Data Pribadi Anda sebagaimana dijelaskan di atas, PT Pusat Gadai Indonesia mungkin perlu mengungkapkan Data Pribadi Anda kepada penyedia layanan pihak ketiga, agen dan/atau afiliasi atau perusahaan terkait PT Pusat Gadai Indonesia, dan/atau pihak ketiga lainnya yang berlokasi di luar wilayah Indonesia. Meskipun demikian, PT Pusat Gadai Indonesia akan memastikan melalui dokumen perjanjian dengan pihak tersebut, bahwa penyedia layanan pihak ketiga, agen dan/atau afiliasi atau perusahaan terkait dan/atau pihak ketiga lainnya tersebut hanya akan mengelola dan/atau memanfaatkan Data Pribadi Anda sehubungan dengan satu atau lebih tujuan sebagaimana diatur dalam Kebijakan Privasi ini dan sesuai dengan ketentuan peraturan perundang-undangan yang berlaku.</p>
    </ul>

    <h2 style="font-size: 18px;">3. Cookie(s)</h2>
    <p>Cookie adalah berkas data kecil yang ditempatkan browser pada perangkat internet Anda. Dengan cookie, situs web yang Anda akses dapat menyimpan informasi atau mengingat tindakan dan preferensi Anda dari waktu ke waktu. Sebagian besar browser internet mendukung cookie; namun Anda dapat mengatur browser yang Anda gunakan untuk menolak beberapa jenis cookie tertentu atau cookie spesifik. Di samping itu, Anda dapat menghapus cookie kapan saja melalui fitur yang terdapat dalam perangkat internet Anda. Terkait dengan penyediaan layanan Aplikasi/Situs Gadai Online, Anda memahami bahwa Kami dapat menggunakan cookie untuk berbagai tujuan. Kami menggunakannya, misalnya, untuk mengingat preferensi penelusuran laman Anda dalam browser Anda, dan keperluan keamanan Anda saat menggunakan Aplikasi/Situs Gadai Online.</p>
    <p>Sebagai informasi bahwa Upaya yang Kami lakukan dalam menyimpan informasi Data Pribadi Anda yaitu dengan cara:</p>
    <ul>
      <li>Mendapatkan persetujuan tegas (explicit consent) secara tertulis atau lisan terekam dari Anda untuk memproses Data Pribadi yang buktinya dapat disimpan dan ditunjukkan;</li>
      <li>Melakukan beberapa upaya yang lazim dalam melindungi keamanan Data Pribadi Anda dari pengaksesan yang tidak sah, pengungkapan yang tidak sah, pengubahan yang tidak sah, penyalahgunaan, perusakan, dan/atau kehilangan Data Pribadi;</li>
    </ul>

    <h2 style="font-size: 18px;">4. Perlindungan Keamanan Data Pribadi dan Keamanan Pembayaran</h2>
    <p>Keamanan informasi Data Pribadi Anda adalah hal yang sangat penting bagi Kami. Aplikasi Gadai Online dan Pusat Gadai Indonesia memastikan bahwa informasi yang dikumpulkan akan disimpan dengan aman, namun harap diketahui bahwa tidak ada metode menyangkut transmisi data melalui internet, atau metode penyimpanan elektronik yang aman. Dengan demikian, Aplikasi Gadai Online dan Pusat Gadai Indonesia tidak dapat menjamin 100% keamanan data yang disediakan atau dikirimkan kepada Aplikasi Gadai Online dan Pusat Gadai Indonesia oleh Anda dan pemberian informasi oleh Anda merupakan risiko yang ditanggung oleh Anda sendiri. Sebagai informasi bahwa Upaya yang Kami lakukan dalam menyimpan informasi Data Pribadi Anda yaitu dengan cara:</p>
    <ul>
      <li>Mendapatkan persetujuan tegas (explicit consent) secara tertulis atau lisan terekam dari Anda untuk memproses Data Pribadi yang buktinya dapat disimpan dan ditunjukkan;</li>
      <li>Melakukan beberapa upaya yang lazim dalam melindungi keamanan Data Pribadi Anda dari pengaksesan yang tidak sah, pengungkapan yang tidak sah, pengubahan yang tidak sah, penyalahgunaan, perusakan, dan/atau kehilangan Data Pribadi.</li>
    </ul>
    <p>Memberitahukan tujuan dan aktivitas pemrosesan, serta kegagalan pelindungan Data Pribadi Anda.<br>
    Mengumpulkan dan memproses Data Pribadi Anda secara terbatas dan spesifik, sah secara hukum, transparan, patut, dapat dipertanggungjawabkan dan sesuai dengan tujuannya.<br>
    Melakukan perekaman terhadap seluruh kegiatan pemrosesan Data Pribadi.<br>
    Menyampaikan pemberitahuan tertulis kepada Anda dan lembaga terkait yang berwenang selambatnya dalam kurun waktu 3x24 jam dalam hal terjadi kegagalan pelindungan Data Pribadi milik Anda.</p>
    <p>Data transaksi Anda hanya disimpan sepanjang diperlukan untuk menyelesaikan transaksi di layanan Kami sesuai dengan ketentuan yang berlaku. Untuk mengetahui lebih lanjut mengenai keamanan pembayaran dan sistem pembayaran di layanan Kami, silahkan Anda membaca Syarat & Ketentuan Layanan Aplikasi Gadai Online dan Pusat Gadai Indonesia.</p>
    <p>Bahwa terdapat kemungkinan bahwa beberapa Data Pribadi Anda disimpan oleh pihak lain, termasuk instansi penyelenggara negara yang berwenang. Dalam hal Pusat Gadai Indonesia membagikan Data Pribadi Anda kepada instansi penyelenggara negara yang berwenang dan/atau instansi lainnya yang dapat ditunjuk oleh pemerintah yang berwenang atau memiliki kerja sama dengan Pusat Gadai Indonesia. Anda menyetujui dan mengakui bahwa penyimpanan Data Pribadi Anda oleh instansi tersebut akan mengikuti kebijakan penyimpanan data masing-masing instansi tersebut.</p>
    <p>Pusat Gadai Indonesia akan menyelidiki keluhan Anda dan berupaya untuk memberikan tanggapan terhadap keluhan tersebut dalam kurun waktu yang wajar setelah menerima keluhan yang disampaikan oleh Anda.</p>
    <p>Jika Anda memiliki kekhawatiran tentang penanganan atau perlakuan Aplikasi Gadai Online dan Pusat Gadai Indonesia terhadap Data Pribadi Anda atau jika Anda yakin bahwa privasinya telah dilanggar. Anda dapat menghubungi Pusat Gadai Indonesia melalui layanan pelanggan Pusat Gadai Indonesia atau kepada kontak Pusat Gadai Indonesia yang tercantum dalam Kebijakan Privasi ini dengan menjelaskan identitas dan sifat keluhan Anda.</p>

    <h2 style="font-size: 18px;">5. Penghapusan dan Pemusnahan Data Pribadi</h2>
    <p>Anda memiliki hak untuk mencabut persetujuan terkait penggunaan data dan informasi pribadi Anda yang telah dikumpulkan dan digunakan oleh Pusat Gadai Indonesia, termasuk untuk menghentikan penggunaan, mengakses Layanan, dan/atau menutup Akun Gadai Digital Anda, dengan memperhatikan ketentuan peraturan perundang-undangan yang berlaku (termasuk persyaratan retensi yang ditetapkan oleh hukum yang berlaku). Dengan melakukan tindakan ini, Anda dengan ini menyatakan bahwa Anda telah memahami konsekuensi serta segala akibat yang mungkin timbul dari penarikan persetujuan Anda sebagai Pemegang Akun Gadai Digital, termasuk namun tidak terbatas pada dampak bahwa Anda mungkin tidak lagi dapat menikmati Aplikasi Gadai Online.</p>
    
    <p>Anda juga berhak untuk mengajukan permohonan penghapusan Data Pribadi Anda kepada kami, sesuai dengan ketentuan peraturan hukum yang berlaku di NKRI.</p>

    <p>Kami memiliki wewenang untuk menyetujui atau menunda permohonan penghapusan Data Pribadi yang diajukan oleh Anda, dengan mempertimbangkan apakah Anda telah mematuhi prosedur internal yang berlaku di Pusat Gadai Indonesia, apakah Anda telah memenuhi hak dan kewajiban Anda yang timbul akibat penggunaan Aplikasi Gadai Online, atau berdasarkan perjanjian terpisah yang mungkin Anda miliki dengan Pusat Gadai Indonesia.</p>

    <p>Kami akan melakukan proses pemrosesan atas permohonan Anda dalam jangka waktu yang wajar sejak permohonan pencabutan persetujuan disampaikan, dan setelahnya kami tidak akan lagi memproses Data Pribadi Anda sesuai dengan persetujuan awal Anda, kecuali jika diwajibkan oleh peraturan perundang-undangan yang berlaku. Harap diperhatikan bahwa dalam hal persetujuan dicabut, Pusat Gadai Indonesia mungkin tidak dapat melaksanakan kewajibannya berdasarkan setiap perjanjian antara Anda dan Pusat Gadai Indonesia. Terkait hal ini, mungkin muncul situasi di mana, akibat dari pencabutan persetujuan Anda, hubungan hukum antara Anda dan Pusat Gadai Indonesia akan berakhir dan tidak dapat diteruskan.</p></p>
    
    <h2 style="font-size: 18px;">6. Perubahan dan Pembaharuan Data Pribadi</h2>
    <p>Dengan mengingat ketentuan peraturan perundang-undangan yang berlaku dan prosedur yang berlaku di Pusat Gadai Indonesia, Anda berhak mengajukan permohonan untuk melakukan perubahan dan/atau pembaharuan Data Pribadi milik Anda yang telah disimpan oleh Pusat Gadai Indonesia yang diperoleh pada saat Anda menggunakan layanan Aplikasi/Situs ini.</p>
    <h2 style="font-size: 18px;">7. Permintaan Informasi Data Pribadi</h2>
    <P>Pusat Gadai Indonesia memberikan hak kepada Anda untuk dapat memperoleh historis Data Pribadi milik Anda yang pernah diserahkan kepada Pusat Gadai Indonesia, dengan mengikuti prosedur yang ditentukan oleh Pusat Gadai Indonesia dan/atau ditentukan berdasarkan ketentuan peraturan perundang-undangan.</P>

    <h2 style="font-size: 18px;">8. Perubahan Kebijakan Privasi</h2>
    <P>Kami dapat memperbaharui Kebijakan Privasi ini dari waktu ke waktu. Pembaharuan atas Kebijakan Privasi ini akan dipublikasikan di Aplikasi/Situs dan/atau media lainnya yang diberikan oleh Anda. Oleh karenanya, Kami menghimbau Anda untuk mengakses Aplikasi/Situs ini secara berkala atas informasi terkini untuk Layanan Pegadaian Digital. Dengan tetap mengakses dan menggunakan layanan Aplikasi/Situs ini, maka Anda dianggap menyetujui perubahan-perubahan dalam Kebijakan Privasi.</P>


    <h2 style="font-size: 18px;">9. Disclaimer</h2>
    <p>Aplikasi/Situs ini adalah sepenuhnya milik Pusat Gadai Indonesia. Seluruh informasi yang terkandung di dalam Aplikasi/Situs ini adalah benar pada saat dimasukkan. Pusat Gadai Indonesia mempunyai hak penuh untuk memuat, tidak memuat, mengedit, dan/atau menghapus informasi yang ada dari waktu ke waktu. Oleh karenanya, Kami menghimbau Anda untuk mengakses Aplikasi/Situs ini guna untuk memperoleh informasi terkini atas Layanan Gadai Online.</p>
    <p>Pusat Gadai Indonesia tidak bertanggung jawab atas tidak tersampaikannya data/informasi yang disampaikan kepada Anda melalui berbagai jenis saluran komunikasi karena faktor kesalahan teknis yang tidak diduga-duga sebelumnya.</p>
    <p>Jika terdapat pengguna Aplikasi/Situs yang memberikan tanggapan atas informasi yang ada di dalam Aplikasi/Situs ini, tetapi tidak terbatas pada pertanyaan, komentar, saran, atau lainnya, maka hal tersebut dianggap sebagai sesuatu yang bukan rahasia dan Pusat Gadai Indonesia tidak mempunyai kewajiban apapun sehubungan dengan tanggapan tersebut serta Pusat Gadai Indonesia memiliki kebebasan untuk memproduksi, menggunakan, memberitahukan, atau membagikan tanggapan tersebut tanpa pembatasan.</p>

    <h2 style="font-size: 18px;">10. Hubungi Kami</h2>
    <P>Jika Anda memiliki pertanyaan mengenai Kebijakan Privasi ini, saran dan keluhan, silahkan hubungi Kami di Call Center (021) 53 666 333</P>
</div>
<?php include 'footer.php';?>
